### ISSUE TITLE
Failed to Run Tests action and Generate Test Reports

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-tools-intellij#976]
When I tested with my `new Mac laptop`, I saw that the `Run Tests` action failed, and the test reports were not generated.

Environment

macOS Sonoma 14.4
Chip Apple M3 Pro
LTI version : 24.0.9 release candidate driver
LSP4IJ : 0.5.0
Maven project

Screen recording of the issue

https://github.com/user-attachments/assets/b1037d53-9685-460c-85d8-e4ae335d5ac6

**Comment by vaisakhkannan** [comment]
NOTE : I found something interesting: I am able to run the tests and view the generated test report using the sample project in our repository https://github.com/OpenLiberty/liberty-tools-intellij/tree/main/src/test/resources/projects/maven/singleModMavenMP . I ran the UI test locally, and it was successful. Similarly, I checked the GHA builds, and they are also passing. However, the problem arises with the new project we generated in openliberty.io. I tested it with the same project that I ran on my previous Mac machine (where the .m2 folder wasn't cleared), and I'm encountering same failures on my new Mac machine as well.

**Comment by JoshwinThomasIBM** [comment]
Similar issue has been observed with Windows machine as well while testing for maven project , below is the error log 

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.363 s <<< FAILURE! -- in PropertiesEndpointIT
[ERROR] PropertiesEndpointIT.testGetProperties -- Time elapsed: 2.255 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Incorrect response code from http://localhost:9080/mavenapptwo ==> expected: <200> but was: <404>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:563)
        at PropertiesEndpointIT.testGetProperties(PropertiesEndpointIT.java:42)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[INFO] 
[INFO] Results:
[INFO]
[ERROR] Failures: 
[ERROR]   PropertiesEndpointIT.testGetProperties:42 Incorrect response code from http://localhost:9080/mavenapptwo ==> expected: <200> but was: <404>
[INFO]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] Rendering content with org.apache.maven.skins:maven-fluido-skin:jar:2.0.0-M9 skin
[ERROR] Failed to run integration tests
io.openliberty.tools.common.plugins.util.PluginExecutionException: Failed to run integration tests
    at io.openliberty.tools.maven.server.DevMojo$DevMojoUtil.runIntegrationTests (DevMojo.java:1290)
    at io.openliberty.tools.common.plugins.util.DevUtil.runTests (DevUtil.java:673)
    at io.openliberty.tools.common.plugins.util.DevUtil$TestJob.run (DevUtil.java:5318)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:842)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to execute mojo
    at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo (MojoExecutor.java:122)
    at io.openliberty.tools.maven.server.DevMojo.runTestMojo (DevMojo.java:1867)
    at io.openliberty.tools.maven.server.DevMojo.access$7200 (DevMojo.java:87)
    at io.openliberty.tools.maven.server.DevMojo$DevMojoUtil.runIntegrationTests (DevMojo.java:1283)
    at io.openliberty.tools.common.plugins.util.DevUtil.runTests (DevUtil.java:673)
    at io.openliberty.tools.common.plugins.util.DevUtil$TestJob.run (DevUtil.java:5318)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:842)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution null of goal org.apache.maven.plugins:maven-surefire-report-plugin:3.5.0:failsafe-report-only failed: Cannot invoke "Object.toString()" because "value" is null
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:133)
    at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo (MojoExecutor.java:120)
    at io.openliberty.tools.maven.server.DevMojo.runTestMojo (DevMojo.java:1867)
    at io.openliberty.tools.maven.server.DevMojo.access$7200 (DevMojo.java:87)
    at io.openliberty.tools.maven.server.DevMojo$DevMojoUtil.runIntegrationTests (DevMojo.java:1283)
    at io.openliberty.tools.common.plugins.util.DevUtil.runTests (DevUtil.java:673)
    at io.openliberty.tools.common.plugins.util.DevUtil$TestJob.run (DevUtil.java:5318)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:842)
Caused by: java.lang.NullPointerException: Cannot invoke "Object.toString()" because "value" is null
    at org.apache.maven.doxia.sink.impl.SinkUtils.getAttributeString (SinkUtils.java:188)
    at org.apache.maven.doxia.sink.impl.AbstractXmlSink.writeStartTag (AbstractXmlSink.java:126)
    at org.apache.maven.doxia.sink.impl.Xhtml5BaseSink.writeStartTag (Xhtml5BaseSink.java:1647)
    at org.apache.maven.doxia.sink.impl.AbstractXmlSink.writeStartTag (AbstractXmlSink.java:95)
    at org.apache.maven.doxia.sink.impl.Xhtml5BaseSink.anchor (Xhtml5BaseSink.java:1204)
    at org.apache.maven.doxia.sink.impl.AbstractSink.anchor (AbstractSink.java:354)
    at org.apache.maven.reporting.AbstractMavenReportRenderer.startSection (AbstractMavenReportRenderer.java:132)
    at org.apache.maven.reporting.AbstractMavenReportRenderer.startSection (AbstractMavenReportRenderer.java:116)
    at org.apache.maven.plugins.surefire.report.SurefireReportRenderer.renderSectionPackages (SurefireReportRenderer.java:220)
    at org.apache.maven.plugins.surefire.report.SurefireReportRenderer.renderBody (SurefireReportRenderer.java:119)
    at org.apache.maven.reporting.AbstractMavenReportRenderer.render (AbstractMavenReportRenderer.java:93)
    at org.apache.maven.plugins.surefire.report.AbstractSurefireReport.executeReport (AbstractSurefireReport.java:159)
    at org.apache.maven.reporting.AbstractMavenReport.generate (AbstractMavenReport.java:354)
    at org.apache.maven.reporting.AbstractMavenReport.reportToSite (AbstractMavenReport.java:262)
    at org.apache.maven.reporting.AbstractMavenReport.execute (AbstractMavenReport.java:208)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo (MojoExecutor.java:120)
    at io.openliberty.tools.maven.server.DevMojo.runTestMojo (DevMojo.java:1867)
    at io.openliberty.tools.maven.server.DevMojo.access$7200 (DevMojo.java:87)
    at io.openliberty.tools.maven.server.DevMojo$DevMojoUtil.runIntegrationTests (DevMojo.java:1283)
    at io.openliberty.tools.common.plugins.util.DevUtil.runTests (DevUtil.java:673)
    at io.openliberty.tools.common.plugins.util.DevUtil$TestJob.run (DevUtil.java:5318)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:842)
[INFO] To run tests on demand, press Enter.

**Comment by vaisakhkannan** [comment]
@TrevCraw , @turkeylurkey  Just for confirmation, I am getting the same exception even for a successful test case when executing `Liberty: run tests`.

<img width="1660" alt="Screenshot 2024-09-18 at 3 38 41 PM" src="https://github.com/user-attachments/assets/9bfa6ac4-3cff-436b-b017-2378962ab11d">

logs:

 
```
[INFO] Running unit tests...
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running JUnit5ExampleTest
This test method should be run
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 s -- in JUnit5ExampleTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] Rendering content with org.apache.maven.skins:maven-fluido-skin:jar:2.0.0-M9 skin
[ERROR] Failed to run unit tests
io.openliberty.tools.common.plugins.util.PluginExecutionException: Failed to run unit tests
    at io.openliberty.tools.maven.server.DevMojo$DevMojoUtil.runUnitTests (DevMojo.java:1273)
    at io.openliberty.tools.common.plugins.util.DevUtil.runTests (DevUtil.java:595)
    at io.openliberty.tools.common.plugins.util.DevUtil$TestJob.run (DevUtil.java:5318)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:840)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to execute mojo
    at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo (MojoExecutor.java:122)
    at io.openliberty.tools.maven.server.DevMojo.runTestMojo (DevMojo.java:1867)
    at io.openliberty.tools.maven.server.DevMojo.access$7200 (DevMojo.java:87)
    at io.openliberty.tools.maven.server.DevMojo$DevMojoUtil.runUnitTests (DevMojo.java:1267)
    at io.openliberty.tools.common.plugins.util.DevUtil.runTests (DevUtil.java:595)
    at io.openliberty.tools.common.plugins.util.DevUtil$TestJob.run (DevUtil.java:5318)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:840)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution null of goal org.apache.maven.plugins:maven-surefire-report-plugin:3.5.0:report-only failed: Cannot invoke "Object.toString()" because "value" is null
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:133)
    at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo (MojoExecutor.java:120)
    at io.openliberty.tools.maven.server.DevMojo.runTestMojo (DevMojo.java:1867)
    at io.openliberty.tools.maven.server.DevMojo.access$7200 (DevMojo.java:87)
    at io.openliberty.tools.maven.server.DevMojo$DevMojoUtil.runUnitTests (DevMojo.java:1267)
    at io.openliberty.tools.common.plugins.util.DevUtil.runTests (DevUtil.java:595)
    at io.openliberty.tools.common.plugins.util.DevUtil$TestJob.run (DevUtil.java:5318)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "Object.toString()" because "value" is null
    at org.apache.maven.doxia.sink.impl.SinkUtils.getAttributeString (SinkUtils.java:188)
    at org.apache.maven.doxia.sink.impl.AbstractXmlSink.writeStartTag (AbstractXmlSink.java:126)
    at org.apache.maven.doxia.sink.impl.Xhtml5BaseSink.writeStartTag (Xhtml5BaseSink.java:1647)
    at org.apache.maven.doxia.sink.impl.AbstractXmlSink.writeStartTag (AbstractXmlSink.java:95)
    at org.apache.maven.doxia.sink.impl.Xhtml5BaseSink.anchor (Xhtml5BaseSink.java:1204)
    at org.apache.maven.doxia.sink.impl.AbstractSink.anchor (AbstractSink.java:354)
    at org.apache.maven.reporting.AbstractMavenReportRenderer.startSection (AbstractMavenReportRenderer.java:132)
    at org.apache.maven.reporting.AbstractMavenReportRenderer.startSection (AbstractMavenReportRenderer.java:116)
    at org.apache.maven.plugins.surefire.report.SurefireReportRenderer.renderSectionPackages (SurefireReportRenderer.java:220)
    at org.apache.maven.plugins.surefire.report.SurefireReportRenderer.renderBody (SurefireReportRenderer.java:119)
    at org.apache.maven.reporting.AbstractMavenReportRenderer.render (AbstractMavenReportRenderer.java:93)
    at org.apache.maven.plugins.surefire.report.AbstractSurefireReport.executeReport (AbstractSurefireReport.java:159)
    at org.apache.maven.reporting.AbstractMavenReport.generate (AbstractMavenReport.java:354)
    at org.apache.maven.reporting.AbstractMavenReport.reportToSite (AbstractMavenReport.java:262)
    at org.apache.maven.reporting.AbstractMavenReport.execute (AbstractMavenReport.java:208)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo (MojoExecutor.java:120)
    at io.openliberty.tools.maven.server.DevMojo.runTestMojo (DevMojo.java:1867)
    at io.openliberty.tools.maven.server.DevMojo.access$7200 (DevMojo.java:87)
    at io.openliberty.tools.maven.server.DevMojo$DevMojoUtil.runUnitTests (DevMojo.java:1267)
    at io.openliberty.tools.common.plugins.util.DevUtil.runTests (DevUtil.java:595)
    at io.openliberty.tools.common.plugins.util.DevUtil$TestJob.run (DevUtil.java:5318)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:840)
[INFO] Waiting up to 30 seconds to find the application start up or update message...
[INFO] CWWKM2010I: Searching for (CWWKZ0001I:|CWWKZ0003I:) in /Users/vaisakht/Documents/DEVEX/intellij/testing/24.0.9-testing/24.0.9-smoke-test/maven-parent/maven-second/app-name-maven-second/target/liberty/wlp/usr/servers/defaultServer/logs/messages.log. This search will timeout after 30 seconds.
[INFO] CWWKM2015I: Match number: 1 is [18/09/24, 15:32:37:676 IST] 00000036 com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application app-name-maven-second started in 0.728 seconds..
[INFO] Running integration tests...
[INFO] Skipping org.apache.maven.plugins:maven-surefire-report-plugin:RELEASE:failsafe-report-only report goal
[INFO] No tests to run.
[INFO] Integration tests finished.
[INFO] 
[INFO] To run tests on demand, press Enter.
```

**Comment by TrevCraw** [comment]
@vaisakhkannan what project are you using? What version of the Liberty Maven Plugin (LMP)? What version of Java?

It looks like the exception is coming from the `maven-surefire-report-plugin`, which is showing in the logs as version `3.5.0`.

**Comment by vaisakhkannan** [comment]
When I searched for the error in the terminal logs, I found an issue https://issues.apache.org/jira/browse/SUREFIRE-2257 that appears to have been fixed, and the fix will be available in version 3.5.1.

**Comment by JoshwinThomasIBM** [comment]
The exception happens due to the surefire-report-parser version 3.5.0, downgrading this to 3.4.0 as a workaround can avoid this exception.  The complete fix will be available once the version 3.5.1 is out . 

You will just need to add the below plugin to the pom that will force maven to download the surefire-report-parser with version 3.4.0 
<plugin>    
      <groupId>org.apache.maven.plugins</groupId>     
      <artifactId>maven-surefire-report-plugin</artifactId>     
     <version>3.4.0</version> 
</plugin>

**Comment by vaisakhkannan** [comment]
I tested with `Liberty-tools-vscode` as well, and it also pulls the latest version (3.5.1) of the maven-surefire-report plugin.

**Comment by JoshwinThomasIBM** [comment]
When i tested this in my local  it always pulled the 3.5.0 version if i don't explicitly specify which version to download , and also got the exception because of this . This can be an issue with my local setup .

**Comment by JoshwinThomasIBM** [comment]
@turkeylurkey if it is mentioned specifically to use 3.5.0 then we still have this issue , if local m2 is cleared and if we do a build it pulls the latest version (3.5.2) and in this case there won't be any exception

**Comment by vaisakhkannan** [comment]
@turkeylurkey , I tested it today. By default, if we use a brand-new Open Liberty project (nothing specified related to  Maven Surefire Plugin in pom.xml) , our Liberty tools automatically pull the latest version of the Maven Surefire Plugin (currently 3.5.2)

<img width="1390" alt="Screenshot 2024-12-03 at 4 32 45 PM" src="https://github.com/user-attachments/assets/36ea2038-68b6-4c05-90fc-934406d00b39">

Then I tried to reproduce the issue by specifying Maven Surefire Plugin version `3.5.0` in the pom.xml. I was able to receive the exception mentioned in this issue.
It seems the problem occurs only with version `3.5.0`.

This issue arises solely due to version `3.5.0`. If a user encounters this problem, they can follow below step to resolve it:

```
Delete the Surefire folder located at `.m2/repository/org/apache/maven/surefire`. This is part of clearing the cache.After that, Liberty tools will automatically pull the latest Maven Surefire Plugin version during the next build.
This should resolve the issue. Ensure that not specify Maven Surefire Plugin version `3.5.0` in your pom.xml.
```

@turkeylurkey , Do you think we need to add this to our wiki pages or README file?

**Comment by turkeylurkey** [comment]
Wiki

**Comment by vaisakhkannan** [comment]
I shared the box note draft of the Wiki page with Trevor, and he reviewed it and made some changes.
@TrevCraw, do you think we should close this issue only after updating the Wiki page?"

**Comment by turkeylurkey** [comment]
@vaisakhkannan  If you have an acceptable wiki page entry please add it to the wiki and then close this issue.

**Comment by vaisakhkannan** [comment]
@turkeylurkey , I have updated the wiki page [Known Problems and Limitations](https://github.com/OpenLiberty/liberty-tools-intellij/wiki/Known-Problems-and-Limitations) based on @TrevCraw  final edits. Please take a look (check second one), I am closing this issue. Thanks
